-- MySQL Script generated by MySQL Workbench
-- Sat Dec 23 15:18:17 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`t_usertype`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`t_usertype` ;

CREATE TABLE IF NOT EXISTS `mydb`.`t_usertype` (
  `id` INT NOT NULL COMMENT '主键id',
  `name` VARCHAR(45) NOT NULL COMMENT '名字',
  `anthority` INT NOT NULL DEFAULT 0 COMMENT '权限',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '用户类型';


-- -----------------------------------------------------
-- Table `mydb`.`t_address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`t_address` ;

CREATE TABLE IF NOT EXISTS `mydb`.`t_address` (
  `id` INT NOT NULL COMMENT '主键id',
  `longitudes` FLOAT NOT NULL COMMENT '经度',
  `latitudes` FLOAT NOT NULL COMMENT '纬度',
  `addressCode` VARCHAR(45) NULL COMMENT '地址编码',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '地理位置信息表';


-- -----------------------------------------------------
-- Table `mydb`.`t_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`t_user` ;

CREATE TABLE IF NOT EXISTS `mydb`.`t_user` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `userName` VARCHAR(45) NULL COMMENT '用户名',
  `password` VARCHAR(45) NULL COMMENT '密码\n',
  `birthday` DATE NULL COMMENT '出生日期',
  `telephone` VARCHAR(45) NULL COMMENT '电话号码',
  `avatar` MEDIUMBLOB NULL COMMENT '头像',
  `email` VARCHAR(45) NULL COMMENT '邮箱',
  `question` VARCHAR(45) NULL COMMENT '密保问题',
  `answer` VARCHAR(45) NULL COMMENT '密保答案',
  `userType` INT NOT NULL COMMENT '用户类型',
  `idCardNo` VARCHAR(45) NULL COMMENT '身份证号码',
  `realName` VARCHAR(45) NULL,
  `signature` VARCHAR(45) NULL COMMENT '个性签名',
  `nikename` VARCHAR(45) NULL COMMENT '昵称',
  `sex` INT NULL COMMENT '性别',
  `addressId` INT NULL COMMENT '家庭地址',
  PRIMARY KEY (`id`),
  INDEX `t_user_t_userType_idx` (`userType` ASC),
  INDEX `t_user_t_address_idx` (`addressId` ASC),
  CONSTRAINT `t_user_t_userType`
    FOREIGN KEY (`userType`)
    REFERENCES `mydb`.`t_usertype` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `t_user_t_address`
    FOREIGN KEY (`addressId`)
    REFERENCES `mydb`.`t_address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '基本用户数据表';


-- -----------------------------------------------------
-- Table `mydb`.`t_department`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`t_department` ;

CREATE TABLE IF NOT EXISTS `mydb`.`t_department` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL COMMENT '部门名字',
  `addressId` INT NULL COMMENT '地址id',
  PRIMARY KEY (`id`),
  INDEX `t_department_address_idx` (`addressId` ASC),
  CONSTRAINT `t_department_address`
    FOREIGN KEY (`addressId`)
    REFERENCES `mydb`.`t_address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '部门表';


-- -----------------------------------------------------
-- Table `mydb`.`t_student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`t_student` ;

CREATE TABLE IF NOT EXISTS `mydb`.`t_student` (
  `id` INT NOT NULL,
  `grade` VARCHAR(45) NULL COMMENT '年级',
  `class` VARCHAR(45) NULL COMMENT '班级',
  `departmentId` INT NULL COMMENT '所在监管部门',
  `guardianId` INT NULL COMMENT '监护人id',
  INDEX `fk_t_student_t_user1_idx` (`id` ASC),
  INDEX `fk_t_student_t_department_idx` (`departmentId` ASC),
  CONSTRAINT `fk_t_student_t_user1`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`t_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_student_t_department`
    FOREIGN KEY (`departmentId`)
    REFERENCES `mydb`.`t_department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '学生表，主要为求救者对象';


-- -----------------------------------------------------
-- Table `mydb`.`t_guardian`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`t_guardian` ;

CREATE TABLE IF NOT EXISTS `mydb`.`t_guardian` (
  `id` INT NOT NULL COMMENT '主键id',
  INDEX `fk_t_guardian_t_user1_idx` (`id` ASC),
  CONSTRAINT `fk_t_guardian_t_user1`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`t_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '监护人员表';


-- -----------------------------------------------------
-- Table `mydb`.`t_gruardian_student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`t_gruardian_student` ;

CREATE TABLE IF NOT EXISTS `mydb`.`t_gruardian_student` (
  `guardianId` INT NOT NULL COMMENT '监护人id',
  `studentId` INT NOT NULL COMMENT '被监护人id，主要为学生',
  PRIMARY KEY (`guardianId`, `studentId`),
  INDEX `t_gruardian_student_studentId_idx` (`studentId` ASC),
  CONSTRAINT `t_gruardian_student_guardianId`
    FOREIGN KEY (`guardianId`)
    REFERENCES `mydb`.`t_guardian` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `t_gruardian_student_studentId`
    FOREIGN KEY (`studentId`)
    REFERENCES `mydb`.`t_student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '监护人和被监护人信息表';


-- -----------------------------------------------------
-- Table `mydb`.`t_request`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`t_request` ;

CREATE TABLE IF NOT EXISTS `mydb`.`t_request` (
  `id` INT NOT NULL,
  `userId` INT NOT NULL COMMENT '用户请求id',
  `requestTime` TIMESTAMP NOT NULL COMMENT '请求时间',
  `addressId` INT NULL COMMENT '请求地址id',
  PRIMARY KEY (`id`),
  INDEX `t_request_address_idx` (`addressId` ASC),
  INDEX `t_request_userId_idx` (`userId` ASC),
  CONSTRAINT `t_request_address`
    FOREIGN KEY (`addressId`)
    REFERENCES `mydb`.`t_address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `t_request_userId`
    FOREIGN KEY (`userId`)
    REFERENCES `mydb`.`t_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '请求求救信息表';


-- -----------------------------------------------------
-- Table `mydb`.`t_supervise`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`t_supervise` ;

CREATE TABLE IF NOT EXISTS `mydb`.`t_supervise` (
  `id` INT NOT NULL COMMENT '主键id',
  `department` INT NULL COMMENT '所在部门',
  `rescueNum` INT NOT NULL DEFAULT 0 COMMENT '营救次数',
  INDEX `t_supervise_department_idx` (`department` ASC),
  INDEX `fk_t_supervise_t_user1_idx` (`id` ASC),
  CONSTRAINT `t_supervise_department`
    FOREIGN KEY (`department`)
    REFERENCES `mydb`.`t_department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_supervise_t_user1`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`t_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '营救者表';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
